import React from 'react'
import Providers from '@/components/providers'
import { Locale, routing } from '@/i18n/routing'
import { Metadata } from 'next'
import { getTranslations, setRequestLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'
import { Almarai } from "next/font/google"
import { Toaster } from '@/components/ui/toaster'
import { cn } from '@/lib/utils/cn'

type LocaleLayoutProps = {
    children: React.ReactNode
    params: { locale: Locale }
}


const AlmaraiFont = Almarai({
    subsets: ['arabic'],
    weight: ['300', '400', '700', '800'],
});

export async function generateMetadata({ params: { locale } }: { params: { locale: Locale } }): Promise<Metadata> {

    const t = await getTranslations({ locale })

    return {
        title: t('metadata_title'),
        description: "Generated by create next app",
    }
}

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

const LocaleLayout = ({ children, params: { locale } }: LocaleLayoutProps) => {
    if (!routing.locales.includes(locale)) notFound();

    // enable static rendering
    setRequestLocale(locale);

    return (
        <>
            <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'} data-theme="light" >
                <body
                    className={cn( AlmaraiFont.className )}               
                     >
                      
                    <Providers>
                        {children}
                        
                        <Toaster />
                    </Providers>
                </body>
            </html>
        </>
    )
}

export default LocaleLayout